--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Jviguy/ZombieOnDeath
build-by-default: true
branches:
- master
projects:
  ZombieOnDeath:
    path: ZombieOnDeath/
    icon: icon/
...
